name: Build FreeBSD Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build FreeBSD Kernel and World
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build FreeBSD in VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: "14.0"
          usesh: true
          envs: |
            MAKEOBJDIRPREFIX=/usr/obj
          sync: rsync
          prepare: |
            pkg update -f
            pkg install -y git
            git clone https://git.freebsd.org/src.git /usr/src
            cd /usr/src
            git checkout 390dc369efaaeca2802baf168ddbd7a40e3afcc8
          run: |
            cd /usr/src
            make -j$(sysctl -n hw.ncpu) buildworld
            make -j$(sysctl -n hw.ncpu) buildkernel KERNCONF=GENERIC
            # Stage the kernel for copyback
            mkdir -p /tmp/artifacts
            cp /usr/obj/usr/src/amd64.amd64/sys/GENERIC/kernel /tmp/artifacts/
          copyback: |
            mkdir -p ${{ github.workspace }}/artifacts
            cp /tmp/artifacts/kernel ${{ github.workspace }}/artifacts/

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: freebsd-kernel
          path: ${{ github.workspace }}/artifacts/kernel
          if-no-files-found: error
