name: Build FreeBSD pf Module

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-pf:
    runs-on: ubuntu-latest
    steps:
      - name: Run FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: "14.0"
          prepare: |
            pkg install -y git 
          run: |
            git clone https://git.freebsd.org/src.git freebsd-src
            cd freebsd-src
            git checkout 390dc369efaaeca2802baf168ddbd7a40e3afcc8
            cd sys/modules/pf
            make || { echo "Build failed"; exit 1; }
            mkdir -p $GITHUB_WORKSPACE/artifacts
            cp pf.ko $GITHUB_WORKSPACE/artifacts/
            
      - name: Upload pf.ko
        uses: actions/upload-artifact@v4
        with:
          name: pf-module
          path: $GITHUB_WORKSPACE/artifacts/pf.ko
          if-no-files-found: error # Fail the workflow if the artifact is missing
